### ISSUE TITLE
Clarify Register Concatination

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/click4#2]
I know the `+` sign is confusing, but it's more of a concatenation as opposed to an addition.

Sort of the 1+1=11 kind of thing, considering it's two registers. Do you think that 16*RX is better notation, or perhaps we could use a different symbol?

**Comment by sparr** [comment]
*16 makes sense to me

**Comment by josefnpat** [comment]
I think the short descriptions might have fixed this for now. Using X[ARG1,ARG2] to mean X[16*ARG1+ARG2]
